### ISSUE TITLE
Let's user input the device IP in case of failed detection on current HA LAN

### ISSUE THREAD

**Issue by PhilippeRaven** [Refoss/refoss-homeassistant#2]
As a lot of others integrations, please let the user the possibility to input the hostname/IP of the device, as it can be on another VLAN.

Thanks a lot !

**Comment by PhilippeRaven** [comment]
Replying to my own ticket, the Meross_lan integration handles the Refoss EM06, so it's a perfectly working solution instead !

**Comment by PhilippeRaven** [comment]
Replying to my own ticket, the Meross_lan integration handles the Refoss EM06, so it's a perfectly working solution instead !

**Comment by iandees** [comment]
Thank you from April 2025! This pointer helped me get my Refoss EM16 working.
